"""
Pydantic models for structured AI outputs.
"""

from typing import Literal

from pydantic import BaseModel, Field


class TicketClassification(BaseModel):
    """
    Structured output returned by the Ticket Classification Agent.
    """

    category: Literal[
        "Billing",
        "Shipping",
        "Technical Support",
        "Account",
        "Refund",
        "General Inquiry",
        "Complaint",
    ] = Field(description="Primary ticket category")

    sentiment: Literal[
        "Positive",
        "Neutral",
        "Frustrated",
        "Angry",
    ] = Field(description="Customer sentiment")

    urgency: Literal[
        "Low",
        "Medium",
        "High",
    ] = Field(description="Ticket urgency")

    requires_tool: bool = Field(
        description="Whether a database lookup is required"
    )

    tool_name: Literal[
        "fetch_user_profile",
        "fetch_user_orders",
        "none",
    ] = Field(description="Tool to call")


class DraftResponse(BaseModel):
    """
    Structured response generated by the Response Agent.
    """

    response: str = Field(
        description="Professional email reply."
    )